# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for MCP LTA Server
# Builder stage: install dependencies and compile TypeScript
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and source code
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install all dependencies without running prepare scripts, then build
RUN npm ci --ignore-scripts && npm run build

# Production stage: only include compiled files and production dependencies
FROM node:lts-alpine
WORKDIR /app

# Copy built output
COPY --from=builder /app/dist ./dist

# Copy package files to install production dependencies
COPY package.json package-lock.json ./

# Install production dependencies without running any scripts
RUN npm ci --omit=dev --ignore-scripts

# Set default entrypoint
ENTRYPOINT ["node", "dist/index.js"]
