# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Multistage Dockerfile for MCP LTA Server

# Builder stage: install dependencies and build the TypeScript code
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy manifest and source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install all dependencies and build
RUN npm ci
RUN npm run build

# Production stage: include only runtime dependencies and built artifacts
FROM node:lts-alpine AS production
WORKDIR /app

# Copy built artifacts and package files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Install only production dependencies without running prepare scripts
RUN npm ci --production --ignore-scripts

# Set environment
ENV NODE_ENV=production

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
