# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src

# Install all dependencies and build TypeScript
RUN npm ci && npm run build

# Expose nothing (stdio)

# Default command to run the MCP server
CMD ["node", "dist/index.js"]
